'use client';

import { useState } from "react";
import Link from "next/link";
import Script from "next/script";
import TableOfContents from "@/components/TableOfContents";
import Breadcrumbs from "@/components/Breadcrumbs";
import { PaymentModal } from "@/components/PaymentModal";

// FAQ data for rendering and Schema
const faqs = [
  {
    question: "Is a legal notice sent online legally valid and admissible in an Indian court?",
    answer: "Yes, absolutely. A legal notice sent online carries full legal validity and is completely admissible as evidence in Indian courts. Under Section 4 and Section 5 of the Information Technology Act, 2000, electronic records and electronic signatures are given legal recognition on par with physical documents. However, the legal notice must still satisfy core drafting standards, and you must maintain the digital transmission logs, read receipts, or electronic delivery confirmations (such as email headers or blue ticks on WhatsApp) as proof of service. When backed by a certificate under Section 63 of the Bharatiya Sakshya Adhiniyam, 2023 (formerly Section 65B of the Indian Evidence Act, 1872), electronic delivery is fully accepted by judicial authorities."
  },
  {
    question: "Why should a legal notice be sent on an advocate's official letterhead rather than directly by the sender?",
    answer: "While a person can legally draft and send a notice themselves (referred to as a personal notice), sending a notice on an advocate's official letterhead is significantly more effective. An advocate's letterhead indicates to the recipient that you have formally engaged legal counsel and are prepared to escalate the matter to court. Furthermore, advocates are trained to structure the notice using precise legal terminology, cite the correct statutes (such as Section 138 of the NI Act or Section 56 of the Contract Act), and specify the exact timeline for compliance. This formal legal pressure often prompts the recipient to settle the dispute immediately without risking a protracted lawsuit."
  },
  {
    question: "What is the standard compliance window given to a recipient in a legal notice?",
    answer: "The standard compliance window in most legal notices is fifteen (15) days from the date of receipt. This gives the recipient a reasonable opportunity to review the demands, consult their legal counsel, and reply or settle the dues. For specific statutory notices, the timeline is defined by law. For example, a cheque bounce notice under Section 138 of the Negotiable Instruments Act must give the drawer exactly 15 days to make the payment. For notices served to government departments or public officers under Section 80 of the Code of Civil Procedure (CPC), a mandatory two-month (60 days) notice period is required before any suit can be filed."
  },
  {
    question: "How do I prove that the recipient actually received the legal notice?",
    answer: "Proof of service is the most critical element when presenting a legal notice in court. For physical dispatches, the receipt generated by India Post (Speed Post/Registered Post) along with the printed online tracking report showing the 'Item Delivered' status acts as absolute legal proof. Alternatively, a signed Acknowledgment Due (AD) card returned by the postman is accepted. For digital transmissions, proof of service is established via email delivery logs and read receipts, or WhatsApp message delivery screenshots showing double blue ticks, accompanied by a digital certification under the Bharatiya Sakshya Adhiniyam, 2023."
  },
  {
    question: "Can a recipient refuse to accept a physical speed post, and what is the legal impact of refusal?",
    answer: "Yes, recipients sometimes attempt to evade legal notices by refusing to accept the post or by instructing security guards to turn the postman away. Under Indian law, this tactic backfires. The Supreme Court of India has established that if a notice is sent to the correct address via registered post or speed post and is returned with the endorsement 'Refused', 'Left Without Address', or 'House Locked', it is deemed to be served. This is known as 'presumptive service' under Section 27 of the General Clauses Act, 1897. The court will proceed under the assumption that the recipient had notice of the contents but chose to ignore it, which heavily biases the case in favor of the sender."
  },
  {
    question: "What should I do if the recipient does not reply to my legal notice within the deadline?",
    answer: "If the recipient fails to reply to the legal notice or refuses to comply with your demands within the stipulated period (usually 15 days), the next step is to initiate formal legal proceedings. The notice establishes a clear cause of action. Depending on the nature of the dispute, you can file a Summary Suit under Order 37 of the CPC, file a consumer complaint on the e-Daakhil portal, lodge a petition with the MSME Facilitation Council, or file a criminal complaint for cheating or criminal breach of trust. The unanswered legal notice will be presented to the judge as crucial evidence of your bona fide attempts to settle the matter amicably."
  },
  {
    question: "What is a rejoinder notice, and when is it required?",
    answer: "A rejoinder (or reply to a reply) notice is issued when the recipient responds to your initial legal notice with false allegations, counterclaims, or an incorrect statement of facts. If the recipient's reply contains statements that could harm your legal position if left unchallenged, your advocate will draft a rejoinder. The rejoinder formally refutes their claims, clarifies the factual inaccuracies in their reply, and re-establishes your original demands. It ensures that the record is clear before you file a formal lawsuit."
  },
  {
    question: "Can I send a legal notice to an employer who is withholding my relieving documents?",
    answer: "Yes. Experience certificates, relieving letters, and salary statements are the personal professional property of the employee. An employer cannot legally hold these documents hostage to coerce you into settling financial disputes or dropping labor claims. A well-drafted legal notice from an advocate can demand the immediate release of these documents, highlighting that withholding them violates your fundamental right to livelihood under Article 21 of the Constitution and can make the employer liable for professional damages."
  },
  {
    question: "How much does it cost to send a legal notice online in India?",
    answer: "At LegalRecovery, we follow a transparent, flat-pricing model for online legal notices. Unlike traditional law firms that charge hourly consultation rates, our online process includes advocate consultation, drafting of the notice, legal vetting, physical printing, dispatch via Speed Post/Registered Post, and real-time tracking updates, all for a single, upfront flat fee. This makes professional legal notices accessible to individuals, startups, and small businesses alike."
  },
  {
    question: "Can a legal notice be sent to a company registered under a foreign jurisdiction?",
    answer: "Yes, a legal notice can be served to an international or foreign entity. However, the process is more complex. If the foreign company has a registered subsidiary, branch office, or designated agent in India, the notice can be served directly to that Indian address. If the entity has no physical presence in India, the notice must be sent to their international headquarters via international registered post or official email channels, citing the relevant clauses of the agreement and international contract principles. If the contract specifies Indian jurisdiction and governing law, the notice remains a powerful precursor to local arbitration or civil recovery."
  }
];

const reviews = [
  {
    id: "rev-ln-1",
    name: "Dr. Alok Sen (Senior Consultant)",
    rating: 5,
    review: "I had a flat booking refund dispute of ₹4.5 Lakhs with a builder who kept ignoring my calls. I used LegalRecovery's online service. An advocate drafted a comprehensive notice citing RERA rules and served it to the builder's office. Within 10 days of receiving the Speed Post, the builder's legal team contacted me and processed my full refund. Saving the hassle of physical lawyer visits was a huge relief!"
  },
  {
    id: "rev-ln-2",
    name: "Riddhima Kapoor (B2B Vendor)",
    rating: 5,
    review: "A commercial client delayed our invoice payments for six months, citing accounting issues. LegalRecovery drafted a professional notice on advocate letterhead and dispatched it. The client realized we were taking legal steps and settled the outstanding dues of ₹2.8 Lakhs with interest within the 15-day compliance window. Exceptional legal-tech service!"
  },
  {
    id: "rev-ln-3",
    name: "Abhinav Reddy (Software Engineer)",
    rating: 5,
    review: "My previous employer refused to pay my last month's salary and withheld my relieving letter after I resigned. LegalRecovery helped me send an online notice. They dispatched the physical notice via Speed Post and also served it via email. The company sent my documents and cleared my pending salary within a week. Highly recommended!"
  },
  {
    id: "rev-ln-4",
    name: "Sukhdev Singh (Landlord)",
    rating: 5,
    review: "A commercial tenant vacated my property without paying three months of rent and refused to return the keys. LegalRecovery's legal notice demanded the rent arrears and warned them of civil suits and damages. The tenant handed over the keys and cleared the dues immediately. The tracking updates and draft verification process were very transparent."
  },
  {
    id: "rev-ln-5",
    name: "Komal Shah (E-commerce Seller)",
    rating: 5,
    review: "A distributor bounced a cheque of ₹1.2 Lakhs and refused to answer calls. LegalRecovery drafted a statutory demand notice under Section 138 of the NI Act and sent it. The distributor's lawyer responded with a settlement offer, and the payment was cleared. The flat pricing was very reasonable compared to local law firms."
  },
  {
    id: "rev-ln-6",
    name: "Varun Malhotra (Consumer)",
    rating: 5,
    review: "An appliance brand refused to replace a defective washing machine despite multiple complaints. LegalRecovery served a formal notice for deficiency of service. The brand's customer relations head contacted me, replaced the machine, and covered the notice charges. Sending a notice online is incredibly simple and effective."
  }
];

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://www.legalrecovery.in"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Services",
      "item": "https://www.legalrecovery.in/services"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Send Legal Notice Online India",
      "item": "https://www.legalrecovery.in/send-legal-notice-online-india"
    }
  ]
};

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "Send Legal Notice Online in India: Legal Validity, Drafting & Dispatch Procedure",
  "description": "Exhaustive legal guide on drafting and sending legal notices online in India. Learn about electronic delivery validity under BSA 2023, physical Speed Post tracking, and advocate notice requirements.",
  "image": "https://www.legalrecovery.in/og-send-legal-notice.png",
  "author": {
    "@type": "Organization",
    "name": "Team LegalRecovery",
    "url": "https://www.legalrecovery.in"
  },
  "publisher": {
    "@type": "Organization",
    "name": "LegalRecovery",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.legalrecovery.in/logo.png"
    }
  },
  "datePublished": "2026-06-09",
  "dateModified": "2026-06-09"
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": faqs.map(faq => ({
    "@type": "Question",
    "name": faq.question,
    "acceptedAnswer": {
      "@type": "Answer",
      "text": faq.answer
    }
  }))
};

const reviewSchema = {
  "@context": "https://schema.org",
  "@type": "Product",
  "name": "Online Legal Notice Drafting & Dispatch Service",
  "image": "https://www.legalrecovery.in/og-send-legal-notice.png",
  "description": "Professional assistance for drafting, vetting, and dispatching legal notices on advocate letterhead via Speed Post and digital channels in India.",
  "brand": {
    "@type": "Brand",
    "name": "LegalRecovery"
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.9",
    "reviewCount": "890"
  },
  "review": reviews.map(rev => ({
    "@type": "Review",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": String(rev.rating)
    },
    "author": {
      "@type": "Person",
      "name": rev.name
    },
    "reviewBody": rev.review
  }))
};

export default function SendLegalNoticeClient() {
  const [expandedFaqs, setExpandedFaqs] = useState<string[]>([]);
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);

  const toggleFaq = (index: number) => {
    const faqId = `faq-${index}`;
    setExpandedFaqs((prev) =>
      prev.includes(faqId) ? prev.filter((id) => id !== faqId) : [...prev, faqId]
    );
  };

  const tocSections = [
    { id: "online-notice-legal-validity", title: "1. Legal Validity of Online Legal Notices" },
    { id: "statutory-requirements-advocate", title: "2. Statutory Notice vs. Advocate Letterhead" },
    { id: "step-by-step-digital-drafting", title: "3. Step-by-Step Procedure to Draft Online" },
    { id: "physical-dispatch-india-post", title: "4. Physical Dispatch via Speed Post & Tracking" },
    { id: "digital-delivery-whatsapp-email", title: "5. Digital Service: WhatsApp, Email & BSA 2023" },
    { id: "recipient-response-scenarios", title: "6. Handling Recipient Responses & Refusal" },
    { id: "notice-types-money-consumer", title: "7. Common Legal Notice Categories in India" },
    { id: "success-stories-reviews", title: "8. Success Stories & Client Reviews" },
    { id: "faqs", title: "9. Frequently Asked Questions" }
  ];

  const breadcrumbItems = [
    { label: "Services", href: "/services" },
    { label: "Send Legal Notice Online", href: "/send-legal-notice-online-india" }
  ];

  return (
    <>
      <Script
        id="breadcrumb-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <Script
        id="article-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <Script
        id="faq-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Script
        id="review-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(reviewSchema) }}
      />

      <div className="bg-[#F8F9FB] min-h-screen font-sans text-slate-800 text-left">
        
        {/* Expanded Hero Section */}
        <div className="relative bg-gradient-to-br from-[#111827] via-[#0F172A] to-[#020617] text-white overflow-hidden py-24 md:py-44 border-b border-slate-900">
          <div className="absolute inset-0 bg-black opacity-40 z-10"></div>
          {/* Ambient Red Glow Decorative elements */}
          <div className="absolute top-0 left-0 w-96 h-96 bg-[#DC2626] opacity-20 rounded-full -translate-x-1/2 -translate-y-1/2 z-0 blur-[100px]"></div>
          <div className="absolute bottom-0 right-0 w-96 h-96 bg-[#DC2626] opacity-15 rounded-full translate-x-1/3 translate-y-1/3 z-0 blur-[100px]"></div>
          
          <div className="relative z-20 container mx-auto px-4 text-center">
            <span className="inline-block text-[#DC2626] text-xs md:text-sm font-black uppercase tracking-widest mb-4 bg-red-950/30 px-4 py-1.5 rounded-full border border-[#DC2626]/20">
              India&apos;s Leading Legal-Tech Platform
            </span>
            <h1 className="text-3xl md:text-6xl font-black mb-6 leading-tight tracking-tight">
              Send a Professional <span className="text-[#DC2626]">Legal Notice</span> Online
            </h1>
            <p className="text-sm md:text-xl mb-8 md:mb-12 max-w-3xl mx-auto text-slate-300 leading-relaxed font-medium">
              Settle disputes efficiently without stepping out of your home. Draft custom notices on registered advocate letterheads, dispatch physically via Speed Post with tracking, and serve digitally on WhatsApp & Email. 
            </p>
            <button 
              onClick={() => setIsPaymentModalOpen(true)}
              className="bg-[#DC2626] hover:bg-[#B91C1C] text-white font-extrabold py-4 px-10 md:py-5 md:px-14 rounded-xl transition-all transform hover:scale-[1.02] active:scale-100 shadow-xl shadow-red-950/20 text-sm md:text-lg cursor-pointer animate-pulse-slow"
            >
              Start Recovery Now
            </button>
          </div>
        </div>

        <div className="container mx-auto px-4 max-w-8xl py-10">
          <div className="mb-6">
            <Breadcrumbs items={breadcrumbItems} />
          </div>
          
          <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr_280px] gap-8 items-start mt-6">
            
            {/* Left Sidebar - TOC (Desktop) */}
            <div className="hidden lg:block sticky top-24 max-h-[calc(100vh-120px)] overflow-y-auto pr-2 scrollbar-hide">
              <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-100">
                <TableOfContents sections={tocSections} orientation="vertical" />
              </div>
            </div>

            {/* Main Content Area */}
            <div className="min-w-0">
              {/* TOC (Mobile) */}
              <div className="lg:hidden mb-6 sticky top-20 z-10 scale-90 origin-top">
                <TableOfContents sections={tocSections} />
              </div>

              <div className="bg-white p-6 md:p-12 rounded-3xl shadow-sm space-y-12 border border-slate-100">
                
                {/* 1. Legal Validity of Online Legal Notices */}
                <section id="online-notice-legal-validity" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">1. Legal Validity of Online Legal Notices</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      In the modern judicial landscape of India, technology has transformed traditional legal processes from slow, paper-bound workflows into fast, digitally validated procedures. One of the most frequent questions from individuals, entrepreneurs, and corporations alike is: <strong>&quot;Is a legal notice sent online legally valid under Indian law?&quot;</strong> The answer is an unequivocal yes. The legal validity of digital transmissions is anchored firmly in central legislation, and courts across India—including the Supreme Court—have actively recognized electronic service to bypass geographical delays.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      The primary statutory validation for online legal notices is provided by the <strong>Information Technology Act, 2000</strong>. Under <strong>Section 4</strong> of the IT Act, where any law provides that information or any other matter shall be in writing or in typewritten or printed form, then, notwithstanding anything contained in such law, such requirement shall be deemed to have been satisfied if such information or matter is rendered or made available in an electronic form. Furthermore, <strong>Section 5</strong> of the Act gives legal recognition to electronic signatures. This means that a legal notice drafted digitally, signed electronically by an advocate, and transmitted via electronic channels carries the exact same evidentiary weight as a physically typed paper.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      However, digital validity does not mean that a simple email draft is sufficient. For an online legal notice to be legally robust, it must follow strict guidelines. It must clearly state the facts of the dispute, detail the specific legal violations, specify the exact compensation or relief demanded, and provide a clear timeline for compliance. Additionally, you must maintain a secure record of the transmission logs. Under the <strong>Bharatiya Nyaya Sanhita, 2023 (BNS)</strong> and the <strong>Bharatiya Sakshya Adhiniyam, 2023 (BSA)</strong>, which replaced the old Indian Penal Code and Evidence Act, electronic documents are fully recognized as primary evidence. When presenting an online notice in court, providing the digital receipt accompanied by a statutory electronic certificate ensures that the court accepts the notice as indisputable evidence.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      At LegalRecovery, we combine the legal validity of the digital medium with the security of traditional delivery. We draft the notice digitally, have it verified and signed by a registered advocate from our legal panel, serve it via email and WhatsApp for immediate receipt, and simultaneously dispatch a physical copy on advocate letterhead via India Post Speed Post. This dual-track approach ensures that the recipient cannot evade the notice, providing you with absolute proof of service in a court of law.
                    </p>
                    <div className="bg-red-50 p-6 rounded-2xl border-l-4 border-[#DC2626] italic text-xs sm:text-sm text-red-900 font-semibold leading-relaxed">
                      &quot;Electronic service of legal notices is not just a modern convenience; it is a legally recognized, court-admissible method of dispute resolution under the IT Act, 2000 and the Bharatiya Sakshya Adhiniyam, 2023.&quot;
                    </div>
                  </div>
                </section>

                {/* 2. Statutory Notice vs. Advocate Letterhead */}
                <section id="statutory-requirements-advocate" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">2. Statutory Notice vs. Advocate Letterhead</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      While a legal notice is essentially a formal communication, its legal nature can vary. It is important to distinguish between a **discretionary notice** (sent as a strategic choice to settle a dispute out of court) and a **statutory notice** (which is a mandatory legal prerequisite before a lawsuit can be filed).
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      In many Indian laws, sending a formal demand notice is a strict statutory requirement. If you file a case without serving this notice first, your lawsuit will be dismissed on technical grounds:
                    </p>
                    <div className="space-y-6 pl-4 border-l-2 border-slate-200">
                      <div>
                        <h4 className="text-slate-900 font-extrabold text-sm md:text-base">A. Section 138 of the Negotiable Instruments Act, 1881</h4>
                        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mt-1">
                          In cheque bounce cases, you must serve a statutory demand notice to the drawer within 30 days of receiving the bank return memo. The notice must give the drawer exactly 15 days to clear the payment. If they fail to pay, you have a 30-day window to file a criminal complaint in the Magistrate&apos;s Court. Serving this notice is a mandatory prerequisite for criminal prosecution.
                        </p>
                      </div>
                      <div>
                        <h4 className="text-slate-900 font-extrabold text-sm md:text-base">B. Section 80 of the Code of Civil Procedure (CPC), 1908</h4>
                        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mt-1">
                          If you are filing a civil suit against the Government or a public officer for an act done in their official capacity, you must serve a notice detailing your claim and wait for a mandatory period of two months (60 days) before initiating the lawsuit. This is designed to give the government department an opportunity to resolve the issue administratively.
                        </p>
                      </div>
                      <div>
                        <h4 className="text-slate-900 font-extrabold text-sm md:text-base">C. Section 8 of the Insolvency and Bankruptcy Code (IBC), 2016</h4>
                        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed mt-1">
                          For operational creditors seeking to trigger corporate insolvency proceedings against a defaulting company, serving a Section 8 demand notice is the mandatory first step. The debtor company has 10 days to either pay the outstanding amount or show a pre-existing dispute.
                        </p>
                      </div>
                    </div>
                    <p className="text-sm md:text-base leading-relaxed">
                      Even when not strictly mandatory, issuing a notice on an **advocate&apos;s official letterhead** is critical. A notice sent directly by an individual can easily be dismissed as a personal grievance. However, a notice on an advocate&apos;s letterhead indicates that you have engaged legal professionals and are prepared to escalate the matter to court. Advocates ensure that the notice cites the correct statutes, structures the facts logically, quantifies the claims (including interest and damages) precisely, and gives the recipient a strict deadline to comply, creating the necessary legal pressure for a quick out-of-court settlement.
                    </p>
                  </div>
                </section>

                {/* 3. Step-by-Step Procedure to Draft Online */}
                <section id="step-by-step-digital-drafting" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">3. Step-by-Step Procedure to Draft Online</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      Drafting a legal notice requires a high degree of precision. Any factual error, incorrect date, or vague allegation can be exploited by the recipient&apos;s legal counsel if the matter reaches a court. At LegalRecovery, we have streamlined the online drafting process into a simple, secure workflow that ensures maximum legal accuracy:
                    </p>
                    <div className="bg-slate-50 p-8 rounded-3xl border border-slate-100 space-y-6 text-sm text-slate-650">
                      <div>
                        <span className="font-extrabold text-xs text-[#DC2626] uppercase">Step 1: Fact and Document Gathering</span>
                        <p className="leading-relaxed mt-1.5">
                          Compile all documents supporting your claim. For money recovery, gather invoices, bank statement highlights showing the debit, and written agreements. For tenant disputes, secure the rent agreement. For workplace issues, compile appointment letters and salary slips. This forms the factual foundation of the notice.
                        </p>
                      </div>
                      <div className="border-t border-slate-200 pt-4">
                        <span className="font-extrabold text-xs text-[#DC2626] uppercase">Step 2: Submitting Details Online</span>
                        <p className="leading-relaxed mt-1.5">
                          Enter the details of the dispute on our secure online portal. You will provide the recipient&apos;s correct name and address, a chronological timeline of the events, the total amount claimed, and any supporting files. Our system structures this information for review.
                        </p>
                      </div>
                      <div className="border-t border-slate-200 pt-4">
                        <span className="font-extrabold text-xs text-[#DC2626] uppercase">Step 3: Advocate Drafting and Vetting</span>
                        <p className="leading-relaxed mt-1.5">
                          A registered advocate from our legal panel is assigned to your case. The advocate reviews your documents, drafts the notice on their official letterhead, and integrates the correct legal provisions. A draft copy is shared with you online for verification of dates and facts.
                        </p>
                      </div>
                      <div className="border-t border-slate-200 pt-4">
                        <span className="font-extrabold text-xs text-[#DC2626] uppercase">Step 4: Final Sign-off and Dispatch</span>
                        <p className="leading-relaxed mt-1.5">
                          Once you approve the draft, the advocate signs the physical notice. It is printed on the advocate&apos;s letterhead and prepared for immediate physical and digital dispatch.
                        </p>
                      </div>
                    </div>
                    <p className="text-sm md:text-base leading-relaxed">
                      By moving this process online, we eliminate the need for multiple physical visits to a lawyer&apos;s office, reduce administrative delays, and offer professional legal notices at transparent, flat rates.
                    </p>
                  </div>
                </section>

                {/* 4. Physical Dispatch via Speed Post & Tracking */}
                <section id="physical-dispatch-india-post" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">4. Physical Dispatch via Speed Post &amp; Tracking</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      While digital notices are fast, Indian courts still place the highest reliance on traditional physical delivery methods. The gold standard for serving a legal notice is dispatching it via **India Post Speed Post** or **Registered Post with Acknowledgment Due (AD)**.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      Physical dispatch via India Post offers several distinct advantages in legal proceedings:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Official Government Record:</strong> India Post is a government department. A postal receipt generated by India Post is an official public document that carries a high presumption of genuineness in a court of law.</li>
                      <li><strong>Consignment Tracking:</strong> Every Speed Post is issued a unique 13-digit consignment number (e.g., ET123456789IN). This number allows you to track the real-time status of the parcel on the official India Post tracking portal.</li>
                      <li><strong>Court-Admissible Tracking Reports:</strong> In case of a dispute over whether the notice was served, you can download the official tracking report showing the date, time, and status of delivery (&quot;Item Delivered&quot;). Courts accept this printout as legal proof of service.</li>
                      <li><strong>Acknowledgment Due (AD) Cards:</strong> For Registered Post, a pink AD card is attached to the envelope. Upon delivery, the recipient must sign this card, which is then mailed back to the sender. This physical signature is absolute proof of direct receipt.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      Our automated dispatch system handles this entire process. Once the notice is signed by the advocate, it is physically printed, packaged, and sent via Speed Post. The tracking consignment number is instantly uploaded to your client dashboard, and our system polls the India Post portal to provide you with real-time delivery status updates.
                    </p>
                  </div>
                </section>

                {/* 5. Digital Service: WhatsApp, Email & BSA 2023 */}
                <section id="digital-delivery-whatsapp-email" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">5. Digital Service: WhatsApp, Email &amp; BSA 2023</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      In the digital age, recipients of legal notices often attempt to evade the postman or change physical addresses to escape legal action. To counter this, serving notices digitally via **WhatsApp, Email, or SMS** has become an exceptionally effective strategy.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      The legal framework for electronic service is highly robust:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Judicial Precedents:</strong> In landmark orders, various High Courts and the Supreme Court of India have allowed the service of summons and legal notices through WhatsApp and email. In the case of <i>Kross Television India Pvt. Ltd. v. Vikhyat Chitra Production</i>, the Bombay High Court held that the purpose of a service is to put the other party on notice, and if a message is delivered on WhatsApp and received, it constitutes valid service.</li>
                      <li><strong>Bharatiya Sakshya Adhiniyam, 2023 (BSA):</strong> Under the new BSA framework, electronic records are treated on par with physical documents. Section 63 of the BSA provides a clear procedure for admitting electronic records (such as emails, WhatsApp chat screenshots, and delivery logs) as evidence, provided they are accompanied by a signed electronic certificate verifying that the device used was in proper working order.</li>
                      <li><strong>Immediate Compliance Clock:</strong> While a speed post can take 3 to 5 days to reach, a WhatsApp notice is delivered instantly. The double blue ticks on WhatsApp serve as immediate proof that the recipient has read the notice, starting the 15-day compliance clock without delay.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      When you send a notice through LegalRecovery, we automatically execute electronic service alongside physical dispatch. We send the official PDF notice signed by our advocate to the recipient&apos;s verified email ID and WhatsApp number, and compile a certified electronic evidence report to protect your case.
                    </p>
                  </div>
                </section>

                {/* 6. Handling Recipient Responses & Refusal */}
                <section id="recipient-response-scenarios" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">6. Handling Recipient Responses &amp; Refusal</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      Once a legal notice is delivered, the recipient generally responds in one of three ways. Knowing how to handle each scenario is crucial for maintaining your legal advantage:
                    </p>
                    <div className="space-y-6">
                      <div>
                        <h3 className="text-base md:text-lg font-black text-slate-900 mb-2">Scenario A: The Recipient Refuses or Evades the Post</h3>
                        <p className="text-sm text-slate-650 leading-relaxed">
                          Recipients sometimes instruct security guards to refuse the post or tell the postman they do not reside there. Under Section 27 of the <strong>General Clauses Act, 1897</strong>, and Section 114 of the <strong>Indian Evidence Act, 1872</strong>, if a notice is sent to the correct address via registered/speed post and is returned with the remarks 'Refused' or 'Unclaimed', it is legally deemed as served. The court assumes the recipient has constructive notice, and they cannot claim in court that they were unaware of the dispute.
                        </p>
                      </div>
                      <div>
                        <h3 className="text-base md:text-lg font-black text-slate-900 mb-2">Scenario B: The Recipient Replies with a Counter-Notice</h3>
                        <p className="text-sm text-slate-650 leading-relaxed">
                          Often, the recipient will hire a lawyer to send a reply notice. This reply may contain denials, counter-allegations, or factual inaccuracies designed to weaken your claim. In this scenario, we draft a **Rejoinder (Reply to Reply) Notice**. The rejoinder refutes their false claims, re-establishes your original demands, and ensures that the record is clear before filing a lawsuit.
                        </p>
                      </div>
                      <div>
                        <h3 className="text-base md:text-lg font-black text-slate-900 mb-2">Scenario C: The Recipient Seeks a Settlement</h3>
                        <p className="text-sm text-slate-650 leading-relaxed">
                          This is the most common outcome. Faced with a professional notice on advocate letterhead and the prospect of court litigation, the recipient will contact you or our legal panel to settle. We help structure a formal **Settlement Agreement** to ensure the payment is received securely and all disputes are closed with mutual releases.
                        </p>
                      </div>
                    </div>
                  </div>
                </section>

                {/* 7. Common Legal Notice Categories in India */}
                <section id="notice-types-money-consumer" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">7. Common Legal Notice Categories in India</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      A legal notice must be customized to the specific category of the dispute. Sending a generic notice is ineffective. Below are the most common notice categories we handle online:
                    </p>
                    <ul className="list-disc pl-6 space-y-4 text-sm text-slate-650">
                      <li><strong>Money Recovery (CPC Order 37):</strong> Sent to defaulting debtors, B2B clients, or business partners. It outlines the transaction history, highlights invoices, and demands payment of the principal amount along with interest (usually 18% per annum) within 15 days.</li>
                      <li><strong>Cheque Bounce (NI Act Sec 138):</strong> Sent within 30 days of a cheque bounce. It must give the drawer exactly 15 days to clear the cheque amount. If they fail, criminal proceedings can be initiated.</li>
                      <li><strong>Employment Disputes:</strong> Sent to employers withholding salaries, full and final (FNF) settlements, gratuity, or relieving documents. It highlights labor laws and constitutional rights to livelihood.</li>
                      <li><strong>Landlord-Tenant Issues:</strong> Sent to tenants who default on rent, refuse to vacate after lease expiry, or damage property. It can act as a formal eviction notice under the Transfer of Property Act, 1882.</li>
                      <li><strong>Consumer Grievances:</strong> Sent to brands, e-commerce portals, or service providers for delivering defective products or deficient services, warning them of consumer court filings on e-Daakhil.</li>
                      <li><strong>Real Estate Defaults (RERA):</strong> Sent to builders who delay possession of flats, fail to deliver promised amenities, or refuse refunds for cancellations.</li>
                    </ul>
                  </div>
                </section>

                {/* 8. Success Stories & Client Reviews */}
                <section id="success-stories-reviews" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">8. Success Stories &amp; Reviews</h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      We have helped hundreds of individuals, startups, and small businesses recover payments and resolve disputes. Below are representative success stories:
                    </p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
                      <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                        <span className="text-[#DC2626] text-xs font-black uppercase tracking-wider">Case Study 1: Real Estate Default</span>
                        <h4 className="font-extrabold text-sm text-slate-900 mt-2 mb-3">Recovered ₹4.5 Lakh Flat Advance in Noida</h4>
                        <p className="text-xs text-slate-600 leading-relaxed">
                          A builder delayed possession for 2 years and refused to refund the booking amount. We served a legal notice on advocate letterhead citing RERA provisions. Faced with the threat of regulatory filings, the builder processed a full refund within 10 days of receiving the Speed Post.
                        </p>
                      </div>
                      <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                        <span className="text-[#DC2626] text-xs font-black uppercase tracking-wider">Case Study 2: Unpaid Invoice Recovery</span>
                        <h4 className="font-extrabold text-sm text-slate-900 mt-2 mb-3">Recovered ₹2.8 Lakh Invoice Dues in Bengaluru</h4>
                        <p className="text-xs text-slate-600 leading-relaxed">
                          A client delayed payment on verified invoices for 6 months. We drafted and served a notice warning them of Summary Suits under Order 37 of the CPC. The client settled the dues along with 12% interest within the 15-day compliance window.
                        </p>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
                      {reviews.map((r, i) => (
                        <div key={i} className="p-6 bg-slate-50 rounded-2xl border border-slate-100">
                          <p className="text-sm text-slate-700 italic mb-4">&quot;{r.review}&quot;</p>
                          <h4 className="font-extrabold text-xs text-slate-900">— {r.name}</h4>
                        </div>
                      ))}
                    </div>
                  </div>
                </section>

                {/* 9. FAQs */}
                <section id="faqs" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">9. FAQs</h2>
                  <div className="space-y-4">
                    {faqs.map((faq, idx) => {
                      const faqId = `faq-${idx}`;
                      const isExpanded = expandedFaqs.includes(faqId);
                      return (
                        <div key={idx} className="border border-slate-200 rounded-xl overflow-hidden bg-white shadow-sm transition-all duration-200 hover:border-slate-350">
                          <button
                            onClick={() => toggleFaq(idx)}
                            className="flex justify-between items-center w-full text-left p-4 font-bold text-sm text-slate-900 hover:bg-slate-50/50 focus:outline-none transition-colors cursor-pointer"
                          >
                            <span>{faq.question}</span>
                            <span className={`transform transition-transform duration-205 shrink-0 ml-3 text-slate-400 ${isExpanded ? 'rotate-180' : ''}`}>▼</span>
                          </button>
                          {isExpanded && (
                            <div className="px-4 pb-4 pt-3 text-xs sm:text-sm text-slate-600 leading-relaxed pl-6 border-t border-slate-100 bg-[#F8F9FB]/40">
                              {faq.answer}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </section>

              </div>
            </div>

            {/* Right Sidebar */}
            <div className="space-y-8 sticky top-24">
              <div className="bg-[#111827] p-6 rounded-2xl shadow-sm text-white border border-slate-800 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-24 h-24 bg-red-600/10 rounded-full blur-xl pointer-events-none" />
                <h3 className="text-sm font-black mb-3">Need to Send a Notice?</h3>
                <p className="text-gray-400 mb-5 text-[11px] leading-relaxed">
                  Get your legal notice drafted and vetted by registered advocates on official letterhead with complete tracking support.
                </p>
                <button
                  onClick={() => setIsPaymentModalOpen(true)}
                  className="block w-full bg-[#DC2626] text-white text-center py-3 rounded-xl text-xs font-bold hover:bg-[#B91C1C] transition-colors mb-3 cursor-pointer"
                >
                  Start Recovery Now
                </button>
              </div>
            </div>

          </div>
        </div>
        <PaymentModal isOpen={isPaymentModalOpen} onClose={() => setIsPaymentModalOpen(false)} />
      </div>
    </>
  );
}
