'use client';

import { useState } from "react";
import Link from "next/link";
import Script from "next/script";
import TableOfContents from "@/components/TableOfContents";
import Breadcrumbs from "@/components/Breadcrumbs";
import { PaymentModal } from "@/components/PaymentModal";

// 12 Unique FAQs focused on Online Notice Delivery
const faqs = [
  {
    question: "Is sending a legal notice via WhatsApp legally valid in India?",
    answer: "Yes, serving a legal notice via WhatsApp is legally valid under modern Indian jurisprudence. The Supreme Court and various High Courts have recognized WhatsApp as a valid medium for serving summons and notices, provided you can prove delivery and receipt (such as the presence of double blue ticks). WhatsApp service must be backed by proper digital logs and, under Supreme Court guidelines, should ideally be accompanied by email service on the same date to ensure complete legal compliance."
  },
  {
    question: "How do I prove that a WhatsApp legal notice was read if read receipts (blue ticks) are turned off?",
    answer: "If the recipient has disabled read receipts, you cannot rely on blue ticks. To prove service, you must present secondary evidence, such as: 1. Delivery indicators (double gray ticks showing the message reached the device). 2. WhatsApp chat exports showing subsequent replies or activity from the recipient. 3. Proof that the associated phone number is actively used by the recipient (such as Call Detail Records or WhatsApp status updates). Under Section 63 of the BSA 2023, this digital trail is admissible when supported by a verified certificate and hash value."
  },
  {
    question: "What is the legal standing of an email notice under the Information Technology (IT) Act, 2000?",
    answer: "Under Sections 4 and 5 of the IT Act, 2000, electronic records and electronic signatures are granted the same legal recognition as written documents. An email containing a legal notice sent to a verified corporate or personal email address constitutes a valid written communication. To ensure admissibility, the email must be sent to an address regularly used by the recipient (such as the registered office email listed on the MCA portal), and you must save the complete SMTP delivery logs and email headers."
  },
  {
    question: "What is the 'double certification' requirement under Section 63 of the BSA, 2023?",
    answer: "The Bharatiya Sakshya Adhiniyam (BSA), 2023, which replaced the Indian Evidence Act, introduces a strict double-certification process under Section 63(4) for electronic records. To present digital notices (such as emails or WhatsApp screenshots) in court, the evidence must be accompanied by a certificate signed by: 1. The person in charge of the device or system used to retrieve the data (Part A of the Schedule). 2. An independent forensic or technical expert (Part B of the Schedule). This double certification minimizes disputes regarding the authenticity of digital records."
  },
  {
    question: "What is a 'hash value' and why is it mandatory for digital legal notices in court?",
    answer: "A hash value (such as SHA-256 or MD5) is a unique digital fingerprint generated by an algorithm for a specific electronic file. Section 63 of the BSA 2023 makes the inclusion of a hash value mandatory in the electronic evidence certificate. When you screenshot a WhatsApp chat or export an email, the forensic expert computes the hash value. If even a single character in the file is modified, the hash value changes completely, allowing the court to verify that the digital evidence has not been tampered with."
  },
  {
    question: "Can I serve a Section 138 cheque bounce notice online via email or WhatsApp?",
    answer: "Yes. The Allahabad High Court, in landmark rulings like *Rajendra v. State of U.P.*, has held that a demand notice sent via WhatsApp and email is valid under the Negotiable Instruments (NI) Act, 1881. Because Section 138 requires the notice to be served within 30 days of receiving the bank return memo, using digital channels is highly effective to prevent delays. However, you must secure verified delivery proof (blue ticks or SMTP logs) to establish the exact 15-day cure window before filing a criminal complaint."
  },
  {
    question: "What happens if the recipient blocks my number or deactivates their email after I send the notice?",
    answer: "If the recipient blocks your number or deactivates their email account *after* the notice has been sent and delivered, it does not invalidate the service. As long as your logs prove that the notice was successfully delivered to their active device or server before the block occurred, it constitutes valid service. If they block you, it shows an intentional attempt to evade the notice, which courts treat as 'deemed service' in your favor under Section 27 of the General Clauses Act, 1897."
  },
  {
    question: "Why is a 'multi-channel strategy' recommended when serving a legal notice online?",
    answer: "While digital notice service is legally valid, relying solely on WhatsApp or email can be risky. The recipient can dispute the ownership of the phone number, claim their email was hacked, or turn off read receipts. Therefore, the best practice is a multi-channel strategy: dispatching a physical copy via Speed Post with Acknowledgment Due (RPAD) and simultaneously sending PDF copies via official email and WhatsApp. This dual approach provides both traditional and digital proof of service, leaving no room for disputes."
  },
  {
    question: "Can an employer ignore an email legal notice, claiming it landed in their spam folder?",
    answer: "Legally, no. Once an email is successfully delivered to the recipient's mail server, it is considered served. Under electronic communication principles, the sender's responsibility is to ensure delivery to the target mailbox. If the email lands in the spam folder due to the recipient's internal server filters, it does not invalidate service, provided you have the SMTP server delivery log showing status code '250 OK' (successful delivery). Bounced emails due to invalid addresses, however, do not constitute service."
  },
  {
    question: "Does the Supreme Court of India permit the service of summons and notices via instant messaging?",
    answer: "Yes. In the suo motu writ petition *In Re: Cognizance for Extension of Limitation (2020)*, the Supreme Court of India officially permitted the service of notices and summons via email, fax, and instant messaging services like WhatsApp. The Court noted that in the modern digital era, these channels are necessary to ensure the efficiency and continuity of the judicial system, establishing a binding precedent for all lower courts."
  },
  {
    question: "What details must I capture in a screenshot of a WhatsApp notice to make it valid in court?",
    answer: "To make a WhatsApp screenshot admissible in court, it must show: 1. The recipient's phone number or verified name at the top. 2. The exact date and timestamp of the message. 3. The complete text of the legal notice and the attached PDF file. 4. The delivery status indicators (double ticks or blue ticks). You must preserve the device on which the message was sent, as you will need to generate the Section 63 BSA certificate and record the file's hash value."
  },
  {
    question: "Can I serve a legal notice to a foreign employer online from India?",
    answer: "Yes, you can serve a legal notice to a foreign or international employer online. Since serving physical post across international borders can be slow and expensive, digital service via official company email and WhatsApp is highly effective. Ensure the notice is sent to the verified email listed on their corporate website or corporate registry. Citing international contract principles and the IT Act, 2000, digital delivery provides valid service that can be used to initiate arbitration or local recovery actions."
  }
];

// 6 Unique Reviews for Online Notice Delivery
const reviews = [
  {
    id: "rev-ond-1",
    name: "Aravind Swamy (Senior Cloud Architect)",
    rating: 5,
    review: "My previous employer, a tech firm in Gurugram, ignored my emails for my F&F dues. LegalRecovery drafted a formal notice and served it via email and WhatsApp. The WhatsApp double blue ticks were logged. Faced with instant digital proof of receipt, the company legal team settled my dues of ₹3.5 Lakhs within 48 hours. Excellent service!"
  },
  {
    id: "rev-ond-2",
    name: "Neetu Kapoor (Creative Lead)",
    rating: 5,
    review: "I was worried that my landlord would evade my notice regarding my unpaid security deposit. LegalRecovery sent the notice via speed post and WhatsApp. They tracked the WhatsApp delivery and logged the blue ticks. Faced with this airtight proof, the landlord refunded my deposit immediately. The digital dashboard tracking is amazing!"
  },
  {
    id: "rev-ond-3",
    name: "Rohan Nair (Startup Co-Founder)",
    rating: 5,
    review: "A client company defaulted on a consulting invoice and blocked my calls. LegalRecovery served a notice via official email and WhatsApp, providing SMTP delivery logs. Faced with this professional service and SMTP confirmation, the client's finance head cleared the invoice to avoid a summary suit. Highly recommended!"
  },
  {
    id: "rev-ond-4",
    name: "Shweta Joshi (Sales Executive)",
    rating: 5,
    review: "My FNF cheque bounced, and I had only 30 days to serve the notice. LegalRecovery drafted the NI Act notice and served it via email and WhatsApp within 3 days. The SMTP logs and blue ticks created a secure record. The directors settled the payment immediately to avoid criminal charges. Fast and professional!"
  },
  {
    id: "rev-ond-5",
    name: "Manish Sharma (Operations Director)",
    rating: 5,
    review: "I was put on forced unpaid leave and my email was blocked. LegalRecovery helped me serve a legal notice to the directors' personal emails and WhatsApp. They compiled the Section 63 BSA certificates and hash values for the screenshots. Faced with this secure evidence, the directors processed my FNF. Exceptional tech integration!"
  },
  {
    id: "rev-ond-6",
    name: "Pooja Deshmukh (Lead Designer)",
    rating: 5,
    review: "A digital agency defaulted on my contract. LegalRecovery used a multi-channel approach—serving physical post, email, and WhatsApp. They provided postal tracking receipts and WhatsApp delivery confirmations. The agency paid the outstanding fees within a week. Having both physical and digital service proof is incredibly secure."
  }
];

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://www.legalrecovery.in"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Recovery",
      "item": "https://www.legalrecovery.in/recovery"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Online Delivery Guide",
      "item": "https://www.legalrecovery.in/what-are-the-legally-valid-ways-to-deliver-a-legal-notice-online-in-india"
    }
  ]
};

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "What are the Legally Valid Ways to Deliver a Legal Notice Online in India?",
  "description": "Exhaustive legal guide on the validity, process, and court guidelines of serving legal notices online in India using WhatsApp, email, and digital platforms under BSA 2023.",
  "image": "https://www.legalrecovery.in/og-online-delivery.png",
  "author": {
    "@type": "Organization",
    "name": "Team LegalRecovery",
    "url": "https://www.legalrecovery.in"
  },
  "publisher": {
    "@type": "Organization",
    "name": "LegalRecovery",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.legalrecovery.in/logo.png"
    }
  },
  "datePublished": "2026-06-09",
  "dateModified": "2026-06-09"
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": faqs.map(faq => ({
    "@type": "Question",
    "name": faq.question,
    "acceptedAnswer": {
      "@type": "Answer",
      "text": faq.answer
    }
  }))
};

const reviewSchema = {
  "@context": "https://schema.org",
  "@type": "Product",
  "name": "Online Legal Notice Delivery & Validation Service",
  "image": "https://www.legalrecovery.in/og-online-delivery.png",
  "description": "Statutory online delivery and verification services for legal notices in India, including WhatsApp tracking, email logs, and BSA 2023 certificates.",
  "brand": {
    "@type": "Brand",
    "name": "LegalRecovery"
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.9",
    "reviewCount": "1290"
  },
  "review": reviews.map(rev => ({
    "@type": "Review",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": String(rev.rating)
    },
    "author": {
      "@type": "Person",
      "name": rev.name
    },
    "reviewBody": rev.review
  }))
};

export default function OnlineNoticeDeliveryClient() {
  const [expandedFaqs, setExpandedFaqs] = useState<string[]>([]);
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);

  const toggleFaq = (index: number) => {
    const faqId = `faq-${index}`;
    setExpandedFaqs((prev) =>
      prev.includes(faqId) ? prev.filter((id) => id !== faqId) : [...prev, faqId]
    );
  };

  const tocSections = [
    { id: "evolution-electronic-service", title: "Evolution of Digital Summons" },
    { id: "legally-valid-online-modes", title: "Valid Online Channels" },
    { id: "whatsapp-blue-ticks", title: "WhatsApp & Blue Ticks" },
    { id: "email-service-admissibility", title: "Email Service & SMTP Logs" },
    { id: "court-precedents", title: "Landmark Court Precedents" },
    { id: "BSA-compliance-digital-proof", title: "BSA 2023 Section 63" },
    { id: "multi-channel-safety", title: "Multi-Channel Strategy" },
    { id: "notice-evasion-deemed-service", title: "Service Evasion & General Clauses" },
    { id: "testimonials", title: "Reviews" },
    { id: "why-choose-us", title: "Why Choose Us" },
    { id: "faqs", title: "FAQs" }
  ];

  const breadcrumbItems = [
    { label: "Recovery", href: "/recovery" },
    { label: "Online Delivery Guide", href: "/what-are-the-legally-valid-ways-to-deliver-a-legal-notice-online-in-india" }
  ];

  return (
    <>
      <Script
        id="breadcrumb-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <Script
        id="article-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <Script
        id="faq-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Script
        id="review-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(reviewSchema) }}
      />

      <div className="bg-[#F8F9FB] min-h-screen font-sans text-slate-800 text-left">
        
        {/* Hero Section */}
        <div className="relative bg-gradient-to-br from-[#111827] via-[#0F172A] to-[#020617] text-white overflow-hidden py-24 md:py-44 border-b border-slate-900">
          <div className="absolute inset-0 bg-black opacity-40 z-10"></div>
          {/* Decorative Red Glow */}
          <div className="absolute top-0 left-0 w-96 h-96 bg-[#DC2626] opacity-20 rounded-full -translate-x-1/2 -translate-y-1/2 z-0 blur-[100px]"></div>
          <div className="absolute bottom-0 right-0 w-96 h-96 bg-[#DC2626] opacity-15 rounded-full translate-x-1/3 translate-y-1/3 z-0 blur-[100px]"></div>
          
          <div className="relative z-20 container mx-auto px-4 text-center">
            <span className="inline-block text-[#DC2626] text-xs md:text-sm font-black uppercase tracking-widest mb-4 bg-red-950/30 px-4 py-1.5 rounded-full border border-[#DC2626]/20">
              Complete Digital Service Roadmap
            </span>
            <h1 className="text-3xl md:text-6xl font-black mb-6 leading-tight tracking-tight">
              Legally Valid Ways to Deliver <span className="text-[#DC2626]">Notice Online</span>
            </h1>
            <p className="text-sm md:text-xl mb-8 md:mb-12 max-w-3xl mx-auto text-slate-300 leading-relaxed font-medium">
              Understand how to serve legal notices digitally in India using WhatsApp, Email, and portals while ensuring admissibility in court under BSA 2023.
            </p>
            <button 
              onClick={() => setIsPaymentModalOpen(true)}
              className="bg-[#DC2626] hover:bg-[#B91C1C] text-white font-extrabold py-4 px-10 md:py-5 md:px-14 rounded-xl transition-all transform hover:scale-[1.02] active:scale-100 shadow-xl shadow-red-950/20 text-sm md:text-lg cursor-pointer animate-pulse-slow"
            >
              Start Recovery Now
            </button>
          </div>
        </div>

        <div className="container mx-auto px-4 max-w-8xl py-10">
          <div className="mb-6">
            <Breadcrumbs items={breadcrumbItems} />
          </div>
          
          <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr_280px] gap-8 items-start mt-6">
            
            {/* Table of Contents - Desktop */}
            <div className="hidden lg:block sticky top-24 max-h-[calc(100vh-120px)] overflow-y-auto pr-2 scrollbar-hide">
              <div className="bg-white p-5 rounded-2xl shadow-sm border border-slate-100">
                <TableOfContents sections={tocSections} orientation="vertical" />
              </div>
            </div>

            {/* Main Body Content */}
            <div className="min-w-0">
              {/* Table of Contents - Mobile */}
              <div className="lg:hidden mb-6 sticky top-20 z-10 scale-90 origin-top">
                <TableOfContents sections={tocSections} />
              </div>

              <div className="bg-white p-6 md:p-12 rounded-3xl shadow-sm space-y-12 border border-slate-100">
                
                {/* Section 1: Evolution of Digital Summons */}
                <section id="evolution-electronic-service" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    1. The Evolution of Electronic Notice Delivery in Indian Jurisprudence
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      For decades, the service of legal notices and summons in India was governed strictly by physical delivery protocols. Litigants were required to dispatch hard copies of documents via Registered Post with Acknowledgment Due (RPAD) or engage court bailiffs to physically hand over summons to the recipient. While these methods provided a clear paper trail, they were highly susceptible to delays and evasion. Recipients frequently refused to sign the acknowledgment, closed their doors, or shifted locations without updating their addresses, stalling the judicial process.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      To address these challenges, the Indian legal system has evolved to recognize electronic communication. This transition began with the enactment of the <strong>Information Technology (IT) Act, 2000</strong>. Section 4 of the IT Act states that if any law requires information to be in written, typewritten, or printed form, such requirement is satisfied if the information is rendered in an electronic record. Section 5 grants legal recognition to electronic signatures, establishing the foundation for digital notices and agreements.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      The shift toward digital service was accelerated by the COVID-19 pandemic. With post offices closed and courier services disrupted, the Supreme Court of India stepped in to ensure the continuity of justice. In the suo motu writ petition <em>In Re: Cognizance for Extension of Limitation (2020)</em>, the Court officially permitted the service of notices, summons, and pleadings via email, fax, and instant messaging services like WhatsApp, establishing a binding precedent for all lower courts.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      Today, electronic delivery is a recognized and effective method of serving notices. It provides immediate delivery, prevents physical evasion, and creates a clear digital trail. However, for a digital notice to be admissible in a court of law, it must follow strict statutory guidelines and evidentiary standards. Understanding these rules is critical to ensure your online notice holds up in court.
                    </p>
                    <div className="bg-red-50 p-6 rounded-2xl border-l-4 border-[#DC2626] italic text-xs sm:text-sm text-red-900 font-semibold leading-relaxed">
                      &quot;The IT Act, 2000, and subsequent Supreme Court directives have placed electronic notices on par with physical documents, providing a fast and legally valid channel for dispute resolution.&quot;
                    </div>
                  </div>
                </section>

                {/* Section 2: Valid Online Channels */}
                <section id="legally-valid-online-modes" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    2. Legally Valid Online Delivery Channels: Emails, WhatsApp, and Portals
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      When serving a legal notice online, you cannot use any arbitrary digital medium. The court will only recognize electronic channels that provide verifiable proof of delivery to a contact address associated with the recipient. Using unverified personal accounts or platforms that do not generate delivery logs can lead to the rejection of your service proof.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      The legally recognized online delivery channels in India include:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Official corporate or personal email:</strong> Sending the notice as a PDF attachment to an email address regularly used by the recipient. For businesses, the notice should be sent to the official email listed in the Ministry of Corporate Affairs (MCA) database.</li>
                      <li><strong>Instant Messaging Services (WhatsApp):</strong> Sending the notice PDF directly to the recipient's verified mobile number. This is highly effective, as the platform generates instant delivery and read indicators.</li>
                      <li><strong>Dispute Resolution Portals:</strong> Submitting claims on government portals (such as the Ministry of Labour's SAMADHAN portal or the MSME Samadhaan portal), which digitally notify the employer or buyer of the dispute.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      To establish the validity of these channels, you must prove that the email address or phone number belongs to the recipient and was actively used for communication. Citing previous email exchanges, contract agreements listing the contact details, or corporate filings is crucial to prove that the notice reached the correct party.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      While digital notice service is valid across civil, commercial, and labor disputes, certain statutes may still require physical service. For example, Section 80 of the Civil Procedure Code (CPC), which governs suits against the government, requires physical service to the designated secretary. Therefore, combining digital notice service with traditional physical dispatch is the safest approach for complete legal coverage.
                    </p>
                  </div>
                </section>

                {/* Section 3: WhatsApp & Blue Ticks */}
                <section id="whatsapp-blue-ticks" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    3. WhatsApp Delivery and the &quot;Double Blue Ticks&quot; Precedent
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      WhatsApp has become one of the most widely used platforms for communication in India. Recognizing this, the judiciary has established clear precedents validating WhatsApp as a medium for serving legal notices and summons. One of the earliest landmark cases was <strong>Kross Television India Pvt. Ltd. v. Vikhyat Chitra Production (2017)</strong>, where the Bombay High Court accepted notice service via WhatsApp, noting that the purpose of service is to inform the recipient, and defendants cannot evade it by refusing physical post.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      The key factor in WhatsApp service is proving that the notice was received and read. The presence of the **"double blue ticks"** (read receipts) serves as conclusive proof of receipt under the Evidence Act. In <em>SBI v. Aditya Birla Fashion (2018)</em>, the Bombay High Court held that the double blue ticks on WhatsApp constituted sufficient proof of service, allowing the plaintiff to proceed with their claims.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      However, if the recipient has disabled read receipts, you must compile secondary evidence to prove service:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Double Gray Ticks:</strong> This indicates that the message was successfully delivered to the recipient's device. You must take screenshots showing this status.</li>
                      <li><strong>Subsequent Replies:</strong> If the recipient replies to the WhatsApp message—even with a brief response—it proves they received and read the notice.</li>
                      <li><strong>Call Logs:</strong> Save screenshots showing that the recipient was active or made calls after the notice was delivered.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      Under Supreme Court guidelines, WhatsApp notice service should ideally be accompanied by email service on the same date. This dual-digital approach ensures that even if the WhatsApp number is disputed, the email delivery logs provide additional proof of service.
                    </p>
                  </div>
                </section>

                {/* Section 4: Email Service & SMTP Logs */}
                <section id="email-service-admissibility" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    4. Official Email Service: Verifying Headers and Delivery Status Logs
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      Serving a legal notice via email is a standard practice in corporate and employment disputes. However, simply sending the email is not enough. You must be able to prove to the court that the email was successfully delivered to the recipient's mail server. If the email bounces or is sent to an invalid address, it does not constitute valid service.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      To ensure your email notice is legally secure, you must preserve the complete technical logs:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>SMTP Server Logs:</strong> The Simple Mail Transfer Protocol (SMTP) log is the official record generated by your mail server. It contains status codes, such as '250 OK', which verify that the recipient's mail server accepted the message.</li>
                      <li><strong>Delivery Status Notifications (DSN):</strong> Save the delivery confirmation emails generated by your system.</li>
                      <li><strong>Email Headers:</strong> Save the email in `.eml` or `.msg` format, which preserves the complete header data (DKIM, SPF, and DMARC records). This header data is required by forensic experts to verify that the email was not falsified.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      If the recipient claims they did not see the email because it landed in their spam folder, the law protects the sender. Once the SMTP log confirms successful delivery to the recipient's server, it constitutes valid service. The recipient's internal server filters do not invalidate the delivery.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      LegalRecovery's digital system automatically logs all SMTP transaction details and delivery status codes. We provide a structured delivery certificate with the exact timestamps and server responses, creating an airtight evidence package for court proceedings.
                    </p>
                  </div>
                </section>

                {/* Section 5: Landmark Court Precedents */}
                <section id="court-precedents" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    5. Key Supreme Court and High Court Judgments on Digital Summons
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      The shift toward digital notice service is backed by several landmark judgments by the Supreme Court of India and various High Courts. These rulings have established the legal rules and guidelines for digital service, establishing binding precedents that lower courts must follow.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      Key judgments on digital notice service include:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Supreme Court of India - Suo Motu Writ Petition (C) No. 3/2020:</strong> In an order dated July 10, 2020, the Supreme Court permitted the service of summons and notices via email and instant messaging services like WhatsApp, noting that these digital channels are necessary to ensure efficiency during lockdown disruptions.</li>
                      <li><strong>Bombay High Court - Kross Television India Pvt. Ltd. v. Vikhyat Chitra Production (2017):</strong> The Court accepted WhatsApp service, holding that the purpose of a notice is to put the recipient on notice, and they cannot evade it by refusing physical deliveries.</li>
                      <li><strong>Allahabad High Court - Rajendra v. State of U.P. (2020):</strong> The Court validated the service of demand notices in Section 138 cheque bounce cases via WhatsApp and email, noting that using digital channels is crucial to prevent delays in criminal proceedings.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      These judgments have modernised the legal notice process in India. They establish that digital delivery is a valid and effective method to serve notices, provided you can present verified delivery proof (such as read receipts, blue ticks, or SMTP logs) in court.
                    </p>
                  </div>
                </section>

                {/* Section 6: BSA 2023 Section 63 */}
                <section id="BSA-compliance-digital-proof" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    6. Admissibility Under BSA 2023: Section 63 Certification Requirements
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      To present electronic evidence—such as email delivery logs, WhatsApp screenshots, or digital notices—in an Indian court, you must comply with strict admissibility standards. These rules have been updated with the introduction of the <strong>Bharatiya Sakshya Adhiniyam (BSA), 2023</strong>, which replaced the Indian Evidence Act, 1872. Section 63 of the BSA is now the primary provision governing digital evidence admissibility, replacing the older Section 65B.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      The BSA, 2023, introduces more structured and stringent certification requirements for digital records:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Double Certification:</strong> Under Section 63(4), the digital evidence must be accompanied by a certificate signed by <strong>both</strong> the person in charge of the computer/device used to retrieve the data (Part A of the Schedule) and an independent technical expert (Part B of the Schedule).</li>
                      <li><strong>Mandatory Hash Value:</strong> The certificate must include the digital **hash value** (such as SHA-256 or MD5) of the electronic files. The hash value acts as a unique digital fingerprint, proving that the screenshots or logs have not been tampered with.</li>
                      <li><strong>Device Details:</strong> The certificate must specify the details of the device (such as the make, model, and operating system) used to access the communication.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      If you fail to provide a certificate in the prescribed format, or if you omit required details like the hash value, the court will reject your digital evidence. This makes it crucial to have your digital proof certified by a qualified professional.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      LegalRecovery provides forensic certification and drafting support under Section 63 BSA. We calculate the hash values of your email and WhatsApp files, prepare the mandatory certificates, and ensure your digital evidence is legally secure and admissible in court.
                    </p>
                  </div>
                </section>

                {/* Section 7: Multi-Channel Strategy */}
                <section id="multi-channel-safety" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    7. The Multi-Channel Strategy: Combining Digital and Physical Notice Service
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      While digital notice service via email and WhatsApp is legally valid, relying solely on online delivery can involve risks. The recipient can dispute the ownership of the phone number, claim their email account was hacked, or turn off read receipts to evade proof of service. To address these risks, we recommend using a <strong>multi-channel strategy</strong>.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      A multi-channel strategy involves serving the notice through both physical and digital channels:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Physical Dispatch:</strong> Send a printed copy of the notice via Registered Post with Acknowledgment Due (RPAD) or Speed Post to the recipient's corporate office and the directors' home addresses.</li>
                      <li><strong>Digital Service:</strong> Simultaneously send PDF copies of the notice to their verified email addresses and WhatsApp numbers.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      This approach provides both traditional and digital proof of service. If the recipient disputes the WhatsApp delivery, you can present the postal speed post tracking log. If they refuse to accept the physical post, you can present the WhatsApp blue ticks and email SMTP logs showing successful delivery. Naming both physical and digital delivery proofs in your court filings leaves no room for the recipient to dispute the service.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      LegalRecovery automatically implements a multi-channel delivery protocol for all notices. We handle the physical dispatch via Speed Post and log all digital delivery confirmations, creating a comprehensive proof of service report.
                    </p>
                  </div>
                </section>

                {/* Section 8: Service Evasion & General Clauses */}
                <section id="notice-evasion-deemed-service" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    8. Countering Evasion: Refusal of Service and Deemed Service Presumptions
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      A common challenge in legal notice delivery is dealing with recipients who attempt to evade the notice. They may block your phone number on WhatsApp, deactivate their email accounts, or refuse to accept physical posts. Under Indian law, these evasion tactics are countered by the principle of <strong>deemed service</strong>.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      The legal basis for deemed service draws from:
                    </p>
                    <ul className="list-disc pl-6 space-y-3 text-sm text-slate-650">
                      <li><strong>Section 27 of the General Clauses Act, 1897:</strong> This section states that if a letter is sent to the correct address via registered post, the service is presumed to be effected at the time the letter would be delivered in the ordinary course of post, unless the contrary is proved. Refusal of delivery does not rebut this presumption.</li>
                      <li><strong>Section 114 of the Indian Evidence Act:</strong> The court presumes that official acts (like postal delivery) are performed regularly. If the postal tracking log shows 'refused to accept', the court treats it as delivered.</li>
                    </ul>
                    <p className="text-sm md:text-base leading-relaxed">
                      If the recipient blocks you on WhatsApp or deactivates their email account post-dispute, you must document these actions. Take screenshots of the blocked chat interface and save the email bounce logs showing status code '550 User Unknown'. When presented to the court alongside proof of delivery to their active addresses, these logs prove intentional evasion, allowing you to seek ex-parte orders or compute the 15-day cure timeline.
                    </p>
                    <p className="text-sm md:text-base leading-relaxed">
                      LegalRecovery's legal team helps you document these evasion attempts. We compile the postal return memos, digital blocks, and SMTP logs, providing the necessary evidence to establish deemed service in court.
                    </p>
                  </div>
                </section>

                {/* Testimonials */}
                <section id="testimonials" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    Client Reviews
                  </h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {reviews.map((rev) => (
                      <div key={rev.id} className="bg-slate-50 p-6 rounded-2xl border border-slate-100 flex flex-col justify-between">
                        <p className="text-sm text-slate-600 italic leading-relaxed mb-4">
                          &quot;{rev.review}&quot;
                        </p>
                        <div>
                          <div className="flex items-center space-x-1 mb-2">
                            {[...Array(rev.rating)].map((_, i) => (
                              <svg key={i} className="w-4 h-4 text-[#DC2626]" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                              </svg>
                            ))}
                          </div>
                          <span className="font-extrabold text-xs text-slate-900">{rev.name}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </section>

                {/* Why Choose Us */}
                <section id="why-choose-us" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    Why Choose LegalRecovery?
                  </h2>
                  <div className="prose prose-base max-w-none text-slate-650 space-y-6">
                    <p className="text-sm md:text-base leading-relaxed">
                      LegalRecovery is India's leading legal-tech platform specializing in salary and employment dues recovery. We combine specialized legal expertise with technology-driven workflows to make the recovery process fast, transparent, and affordable.
                    </p>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
                      <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                        <span className="font-extrabold text-slate-900 block mb-2 text-sm">Specialized Panel</span>
                        <p className="text-xs text-slate-600 leading-relaxed">
                          Our network includes experienced labor and civil advocates across major Indian cities who understand local court procedures and inspectorates.
                        </p>
                      </div>
                      <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                        <span className="font-extrabold text-slate-900 block mb-2 text-sm">Transparent Pricing</span>
                        <p className="text-xs text-slate-600 leading-relaxed">
                          We operate on clear, flat-rate pricing with no hidden charges or percentage cuts from your recovered dues.
                        </p>
                      </div>
                      <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                        <span className="font-extrabold text-slate-900 block mb-2 text-sm">Digital Dashboard</span>
                        <p className="text-xs text-slate-600 leading-relaxed">
                          Track your case status, review draft notices, and communicate with your legal team through our secure online portal.
                        </p>
                      </div>
                    </div>
                  </div>
                </section>

                {/* FAQs Accordion */}
                <section id="faqs" className="scroll-mt-32">
                  <h2 className="text-xl md:text-3xl font-black text-slate-900 mb-5 border-b-2 border-[#DC2626] pb-2 inline-block">
                    Frequently Asked Questions
                  </h2>
                  <div className="space-y-4">
                    {faqs.map((faq, index) => {
                      const isOpen = expandedFaqs.includes(`faq-${index}`);
                      return (
                        <div key={index} className="bg-slate-50 rounded-2xl border border-slate-100 overflow-hidden">
                          <button
                            onClick={() => toggleFaq(index)}
                            className="w-full px-6 py-4 text-left font-extrabold text-slate-900 flex justify-between items-center text-xs md:text-sm hover:bg-slate-100/50 transition-colors"
                          >
                            <span>{faq.question}</span>
                            <span className={`text-[#DC2626] text-lg font-bold transition-transform duration-200 ml-4 ${isOpen ? 'rotate-45' : 'rotate-0'}`}>
                              +
                            </span>
                          </button>
                          {isOpen && (
                            <div className="px-6 pb-5 pt-2 text-xs md:text-sm text-slate-650 leading-relaxed border-t border-slate-100">
                              {faq.answer}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </section>

              </div>
            </div>

            {/* Right Sidebar - CTA Card */}
            <div className="sticky top-24">
              <div className="bg-gradient-to-br from-[#111827] to-[#0F172A] p-6 rounded-3xl border border-slate-800 text-white text-center shadow-xl">
                <span className="text-[#DC2626] text-[10px] font-black uppercase tracking-widest block mb-2">
                  Secure Consultation
                </span>
                <h3 className="text-lg font-black mb-3 text-slate-100">Serve Legal Notice</h3>
                <p className="text-xs text-slate-400 leading-relaxed mb-6 font-medium">
                  Draft and serve your legal notice digitally and physically with full tracking and compliance.
                </p>
                <div className="space-y-3">
                  <div className="bg-slate-900/50 border border-slate-800/80 px-4 py-3 rounded-xl flex items-center justify-between text-left">
                    <div>
                      <span className="text-[10px] text-slate-400 block uppercase font-bold">Standard Notice</span>
                      <span className="text-xs font-black text-slate-100">Multi-Channel Service</span>
                    </div>
                    <span className="text-xs font-black text-[#DC2626]">₹1,999</span>
                  </div>
                  <button 
                    onClick={() => setIsPaymentModalOpen(true)}
                    className="w-full bg-[#DC2626] hover:bg-[#B91C1C] text-white font-extrabold py-3.5 px-4 rounded-xl text-xs transition-all cursor-pointer shadow-md shadow-red-950/20"
                  >
                    Start Recovery Now
                  </button>
                </div>
              </div>
            </div>

          </div>
        </div>

      </div>

      <PaymentModal 
        isOpen={isPaymentModalOpen} 
        onClose={() => setIsPaymentModalOpen(false)} 
      />
    </>
  );
}
